### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lizardlynx** [lizardlynx/realtime-web-chat#1]
- [ ] Make contact name and image change, when destination user changes them.
- [ ] Refactor nodejs.
- [ ] Create better style.
- [ ] Add tips.
- [ ] Add eslint.

**Comment by lizardlynx** [comment]
- [ ] Write tests.

**Comment by lizardlynx** [comment]
- [ ] fix mistakes, which appeared after eslint fix.

**Comment by lizardlynx** [comment]
- [ ] Host.
